// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chain enumeration
type Chain int32

const (
	Chain_CHAIN_UNSPECIFIED Chain = 0
	Chain_CHAIN_ETHEREUM    Chain = 1
	Chain_CHAIN_POLYGON     Chain = 2
	Chain_CHAIN_BSC         Chain = 3
	Chain_CHAIN_SOLANA      Chain = 4
	Chain_CHAIN_TON         Chain = 5
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "CHAIN_UNSPECIFIED",
		1: "CHAIN_ETHEREUM",
		2: "CHAIN_POLYGON",
		3: "CHAIN_BSC",
		4: "CHAIN_SOLANA",
		5: "CHAIN_TON",
	}
	Chain_value = map[string]int32{
		"CHAIN_UNSPECIFIED": 0,
		"CHAIN_ETHEREUM":    1,
		"CHAIN_POLYGON":     2,
		"CHAIN_BSC":         3,
		"CHAIN_SOLANA":      4,
		"CHAIN_TON":         5,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_wallet_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file_api_proto_wallet_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{0}
}

// Standardized error response per spec
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GenerateWalletRequest
type GenerateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Chains        []Chain                `protobuf:"varint,2,rep,packed,name=chains,proto3,enum=wallet.Chain" json:"chains,omitempty"`
	WordCount     int32                  `protobuf:"varint,3,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"` // 12, 15, 18, 21, 24
	Passphrase    string                 `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`                 // Optional passphrase for additional security
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWalletRequest) Reset() {
	*x = GenerateWalletRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWalletRequest) ProtoMessage() {}

func (x *GenerateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWalletRequest.ProtoReflect.Descriptor instead.
func (*GenerateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateWalletRequest) GetChains() []Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *GenerateWalletRequest) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *GenerateWalletRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

// GenerateWalletResponse
type GenerateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Mnemonic      string                 `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWalletResponse) Reset() {
	*x = GenerateWalletResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWalletResponse) ProtoMessage() {}

func (x *GenerateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWalletResponse.ProtoReflect.Descriptor instead.
func (*GenerateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GenerateWalletResponse) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *GenerateWalletResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GenerateWalletResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ImportWalletRequest
type ImportWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mnemonic      string                 `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Passphrase    string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"` // Optional passphrase
	Chains        []Chain                `protobuf:"varint,4,rep,packed,name=chains,proto3,enum=wallet.Chain" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportWalletRequest) Reset() {
	*x = ImportWalletRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportWalletRequest) ProtoMessage() {}

func (x *ImportWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportWalletRequest.ProtoReflect.Descriptor instead.
func (*ImportWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ImportWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImportWalletRequest) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *ImportWalletRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *ImportWalletRequest) GetChains() []Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

// ImportWalletResponse
type ImportWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ImportedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=imported_at,json=importedAt,proto3" json:"imported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportWalletResponse) Reset() {
	*x = ImportWalletResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportWalletResponse) ProtoMessage() {}

func (x *ImportWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportWalletResponse.ProtoReflect.Descriptor instead.
func (*ImportWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ImportWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ImportWalletResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ImportWalletResponse) GetImportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ImportedAt
	}
	return nil
}

// GetAddressesRequest
type GetAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Chains        []Chain                `protobuf:"varint,2,rep,packed,name=chains,proto3,enum=wallet.Chain" json:"chains,omitempty"`
	StartIndex    int32                  `protobuf:"varint,3,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesRequest) Reset() {
	*x = GetAddressesRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesRequest) ProtoMessage() {}

func (x *GetAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAddressesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddressesRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetAddressesRequest) GetChains() []Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *GetAddressesRequest) GetStartIndex() int32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *GetAddressesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetAddressesResponse
type GetAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesResponse) Reset() {
	*x = GetAddressesResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesResponse) ProtoMessage() {}

func (x *GetAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAddressesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Address information
type Address struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chain          Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	DerivationPath string                 `protobuf:"bytes,3,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	Index          int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	IsChange       bool                   `protobuf:"varint,5,opt,name=is_change,json=isChange,proto3" json:"is_change,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *Address) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *Address) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Address) GetIsChange() bool {
	if x != nil {
		return x.IsChange
	}
	return false
}

// SignTransactionRequest
type SignTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Chain           Chain                  `protobuf:"varint,2,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	TransactionData []byte                 `protobuf:"bytes,3,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	AddressIndex    int32                  `protobuf:"varint,4,opt,name=address_index,json=addressIndex,proto3" json:"address_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *SignTransactionRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignTransactionRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

func (x *SignTransactionRequest) GetTransactionData() []byte {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

func (x *SignTransactionRequest) GetAddressIndex() int32 {
	if x != nil {
		return x.AddressIndex
	}
	return 0
}

// SignTransactionResponse
type SignTransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	Signature         string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TransactionHash   string                 `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *SignTransactionResponse) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

func (x *SignTransactionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignTransactionResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

// SignMessageRequest
type SignMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AddressIndex  int32                  `protobuf:"varint,3,opt,name=address_index,json=addressIndex,proto3" json:"address_index,omitempty"`
	Chain         Chain                  `protobuf:"varint,4,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *SignMessageRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignMessageRequest) GetAddressIndex() int32 {
	if x != nil {
		return x.AddressIndex
	}
	return 0
}

func (x *SignMessageRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

// SignMessageResponse
type SignMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureHex  string                 `protobuf:"bytes,2,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	MessageHash   string                 `protobuf:"bytes,3,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *SignMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignMessageResponse) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *SignMessageResponse) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

// VerifySignatureRequest
type VerifySignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Chain         Chain                  `protobuf:"varint,4,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureRequest) Reset() {
	*x = VerifySignatureRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureRequest) ProtoMessage() {}

func (x *VerifySignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureRequest.ProtoReflect.Descriptor instead.
func (*VerifySignatureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *VerifySignatureRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *VerifySignatureRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VerifySignatureRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VerifySignatureRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

// VerifySignatureResponse
type VerifySignatureResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsValid          bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	RecoveredAddress string                 `protobuf:"bytes,2,opt,name=recovered_address,json=recoveredAddress,proto3" json:"recovered_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifySignatureResponse) Reset() {
	*x = VerifySignatureResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureResponse) ProtoMessage() {}

func (x *VerifySignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureResponse.ProtoReflect.Descriptor instead.
func (*VerifySignatureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *VerifySignatureResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifySignatureResponse) GetRecoveredAddress() string {
	if x != nil {
		return x.RecoveredAddress
	}
	return ""
}

// GetBalanceRequest
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain         Chain                  `protobuf:"varint,2,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetBalanceRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

// GetBalanceResponse
type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      int32                  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Chain         Chain                  `protobuf:"varint,4,opt,name=chain,proto3,enum=wallet.Chain" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetBalanceResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetBalanceResponse) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_CHAIN_UNSPECIFIED
}

// GetWalletInfoRequest
type GetWalletInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletInfoRequest) Reset() {
	*x = GetWalletInfoRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInfoRequest) ProtoMessage() {}

func (x *GetWalletInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInfoRequest.ProtoReflect.Descriptor instead.
func (*GetWalletInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *GetWalletInfoRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

// GetWalletInfoResponse
type GetWalletInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SupportedChains []Chain                `protobuf:"varint,3,rep,packed,name=supported_chains,json=supportedChains,proto3,enum=wallet.Chain" json:"supported_chains,omitempty"`
	AddressCount    int32                  `protobuf:"varint,4,opt,name=address_count,json=addressCount,proto3" json:"address_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetWalletInfoResponse) Reset() {
	*x = GetWalletInfoResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInfoResponse) ProtoMessage() {}

func (x *GetWalletInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInfoResponse.ProtoReflect.Descriptor instead.
func (*GetWalletInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *GetWalletInfoResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWalletInfoResponse) GetSupportedChains() []Chain {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

func (x *GetWalletInfoResponse) GetAddressCount() int32 {
	if x != nil {
		return x.AddressCount
	}
	return 0
}

func (x *GetWalletInfoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetWalletInfoResponse) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

// Health check messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_wallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{18}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Checks        []*HealthCheck         `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_wallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetChecks() []*HealthCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ok", "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_api_proto_wallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *HealthCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheck) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_proto_wallet_proto protoreflect.FileDescriptor

const file_api_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/wallet.proto\x12\x06wallet\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".wallet.ErrorResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x15GenerateWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x06chains\x18\x02 \x03(\x0e2\r.wallet.ChainR\x06chains\x12\x1d\n" +
	"\n" +
	"word_count\x18\x03 \x01(\x05R\twordCount\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x04 \x01(\tR\n" +
	"passphrase\"\xbb\x01\n" +
	"\x16GenerateWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1a\n" +
	"\bmnemonic\x18\x02 \x01(\tR\bmnemonic\x12-\n" +
	"\taddresses\x18\x03 \x03(\v2\x0f.wallet.AddressR\taddresses\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x01\n" +
	"\x13ImportWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bmnemonic\x18\x02 \x01(\tR\bmnemonic\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\x12%\n" +
	"\x06chains\x18\x04 \x03(\x0e2\r.wallet.ChainR\x06chains\"\x9f\x01\n" +
	"\x14ImportWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12-\n" +
	"\taddresses\x18\x02 \x03(\v2\x0f.wallet.AddressR\taddresses\x12;\n" +
	"\vimported_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"importedAt\"\x90\x01\n" +
	"\x13GetAddressesRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12%\n" +
	"\x06chains\x18\x02 \x03(\x0e2\r.wallet.ChainR\x06chains\x12\x1f\n" +
	"\vstart_index\x18\x03 \x01(\x05R\n" +
	"startIndex\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"E\n" +
	"\x14GetAddressesResponse\x12-\n" +
	"\taddresses\x18\x01 \x03(\v2\x0f.wallet.AddressR\taddresses\"\xa4\x01\n" +
	"\aAddress\x12#\n" +
	"\x05chain\x18\x01 \x01(\x0e2\r.wallet.ChainR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x0fderivation_path\x18\x03 \x01(\tR\x0ederivationPath\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12\x1b\n" +
	"\tis_change\x18\x05 \x01(\bR\bisChange\"\xaa\x01\n" +
	"\x16SignTransactionRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12#\n" +
	"\x05chain\x18\x02 \x01(\x0e2\r.wallet.ChainR\x05chain\x12)\n" +
	"\x10transaction_data\x18\x03 \x01(\fR\x0ftransactionData\x12#\n" +
	"\raddress_index\x18\x04 \x01(\x05R\faddressIndex\"\x91\x01\n" +
	"\x17SignTransactionResponse\x12-\n" +
	"\x12signed_transaction\x18\x01 \x01(\fR\x11signedTransaction\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12)\n" +
	"\x10transaction_hash\x18\x03 \x01(\tR\x0ftransactionHash\"\x95\x01\n" +
	"\x12SignMessageRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12#\n" +
	"\raddress_index\x18\x03 \x01(\x05R\faddressIndex\x12#\n" +
	"\x05chain\x18\x04 \x01(\x0e2\r.wallet.ChainR\x05chain\"{\n" +
	"\x13SignMessageResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12#\n" +
	"\rsignature_hex\x18\x02 \x01(\tR\fsignatureHex\x12!\n" +
	"\fmessage_hash\x18\x03 \x01(\tR\vmessageHash\"\x8f\x01\n" +
	"\x16VerifySignatureRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12#\n" +
	"\x05chain\x18\x04 \x01(\x0e2\r.wallet.ChainR\x05chain\"a\n" +
	"\x17VerifySignatureResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12+\n" +
	"\x11recovered_address\x18\x02 \x01(\tR\x10recoveredAddress\"R\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\x05chain\x18\x02 \x01(\x0e2\r.wallet.ChainR\x05chain\"\x87\x01\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\x05R\bdecimals\x12#\n" +
	"\x05chain\x18\x04 \x01(\x0e2\r.wallet.ChainR\x05chain\"3\n" +
	"\x14GetWalletInfoRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\xa0\x02\n" +
	"\x15GetWalletInfoResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x128\n" +
	"\x10supported_chains\x18\x03 \x03(\x0e2\r.wallet.ChainR\x0fsupportedChains\x12#\n" +
	"\raddress_count\x18\x04 \x01(\x05R\faddressCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_used\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"\x0f\n" +
	"\rHealthRequest\"\x8f\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x06checks\x18\x03 \x03(\v2\x13.wallet.HealthCheckR\x06checks\"\x8d\x01\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*u\n" +
	"\x05Chain\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHAIN_ETHEREUM\x10\x01\x12\x11\n" +
	"\rCHAIN_POLYGON\x10\x02\x12\r\n" +
	"\tCHAIN_BSC\x10\x03\x12\x10\n" +
	"\fCHAIN_SOLANA\x10\x04\x12\r\n" +
	"\tCHAIN_TON\x10\x052\xb2\x05\n" +
	"\rWalletService\x12O\n" +
	"\x0eGenerateWallet\x12\x1d.wallet.GenerateWalletRequest\x1a\x1e.wallet.GenerateWalletResponse\x12I\n" +
	"\fImportWallet\x12\x1b.wallet.ImportWalletRequest\x1a\x1c.wallet.ImportWalletResponse\x12I\n" +
	"\fGetAddresses\x12\x1b.wallet.GetAddressesRequest\x1a\x1c.wallet.GetAddressesResponse\x12R\n" +
	"\x0fSignTransaction\x12\x1e.wallet.SignTransactionRequest\x1a\x1f.wallet.SignTransactionResponse\x12F\n" +
	"\vSignMessage\x12\x1a.wallet.SignMessageRequest\x1a\x1b.wallet.SignMessageResponse\x12R\n" +
	"\x0fVerifySignature\x12\x1e.wallet.VerifySignatureRequest\x1a\x1f.wallet.VerifySignatureResponse\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12L\n" +
	"\rGetWalletInfo\x12\x1c.wallet.GetWalletInfoRequest\x1a\x1d.wallet.GetWalletInfoResponse\x127\n" +
	"\x06Health\x12\x15.wallet.HealthRequest\x1a\x16.wallet.HealthResponseB4Z2github.com/philletio/phillet-wallet-core/api/protob\x06proto3"

var (
	file_api_proto_wallet_proto_rawDescOnce sync.Once
	file_api_proto_wallet_proto_rawDescData []byte
)

func file_api_proto_wallet_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wallet_proto_rawDesc), len(file_api_proto_wallet_proto_rawDesc)))
	})
	return file_api_proto_wallet_proto_rawDescData
}

var file_api_proto_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_wallet_proto_goTypes = []any{
	(Chain)(0),                      // 0: wallet.Chain
	(*ErrorResponse)(nil),           // 1: wallet.ErrorResponse
	(*GenerateWalletRequest)(nil),   // 2: wallet.GenerateWalletRequest
	(*GenerateWalletResponse)(nil),  // 3: wallet.GenerateWalletResponse
	(*ImportWalletRequest)(nil),     // 4: wallet.ImportWalletRequest
	(*ImportWalletResponse)(nil),    // 5: wallet.ImportWalletResponse
	(*GetAddressesRequest)(nil),     // 6: wallet.GetAddressesRequest
	(*GetAddressesResponse)(nil),    // 7: wallet.GetAddressesResponse
	(*Address)(nil),                 // 8: wallet.Address
	(*SignTransactionRequest)(nil),  // 9: wallet.SignTransactionRequest
	(*SignTransactionResponse)(nil), // 10: wallet.SignTransactionResponse
	(*SignMessageRequest)(nil),      // 11: wallet.SignMessageRequest
	(*SignMessageResponse)(nil),     // 12: wallet.SignMessageResponse
	(*VerifySignatureRequest)(nil),  // 13: wallet.VerifySignatureRequest
	(*VerifySignatureResponse)(nil), // 14: wallet.VerifySignatureResponse
	(*GetBalanceRequest)(nil),       // 15: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil),      // 16: wallet.GetBalanceResponse
	(*GetWalletInfoRequest)(nil),    // 17: wallet.GetWalletInfoRequest
	(*GetWalletInfoResponse)(nil),   // 18: wallet.GetWalletInfoResponse
	(*HealthRequest)(nil),           // 19: wallet.HealthRequest
	(*HealthResponse)(nil),          // 20: wallet.HealthResponse
	(*HealthCheck)(nil),             // 21: wallet.HealthCheck
	nil,                             // 22: wallet.ErrorResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),   // 23: google.protobuf.Timestamp
}
var file_api_proto_wallet_proto_depIdxs = []int32{
	22, // 0: wallet.ErrorResponse.details:type_name -> wallet.ErrorResponse.DetailsEntry
	23, // 1: wallet.ErrorResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: wallet.GenerateWalletRequest.chains:type_name -> wallet.Chain
	8,  // 3: wallet.GenerateWalletResponse.addresses:type_name -> wallet.Address
	23, // 4: wallet.GenerateWalletResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: wallet.ImportWalletRequest.chains:type_name -> wallet.Chain
	8,  // 6: wallet.ImportWalletResponse.addresses:type_name -> wallet.Address
	23, // 7: wallet.ImportWalletResponse.imported_at:type_name -> google.protobuf.Timestamp
	0,  // 8: wallet.GetAddressesRequest.chains:type_name -> wallet.Chain
	8,  // 9: wallet.GetAddressesResponse.addresses:type_name -> wallet.Address
	0,  // 10: wallet.Address.chain:type_name -> wallet.Chain
	0,  // 11: wallet.SignTransactionRequest.chain:type_name -> wallet.Chain
	0,  // 12: wallet.SignMessageRequest.chain:type_name -> wallet.Chain
	0,  // 13: wallet.VerifySignatureRequest.chain:type_name -> wallet.Chain
	0,  // 14: wallet.GetBalanceRequest.chain:type_name -> wallet.Chain
	0,  // 15: wallet.GetBalanceResponse.chain:type_name -> wallet.Chain
	0,  // 16: wallet.GetWalletInfoResponse.supported_chains:type_name -> wallet.Chain
	23, // 17: wallet.GetWalletInfoResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 18: wallet.GetWalletInfoResponse.last_used:type_name -> google.protobuf.Timestamp
	23, // 19: wallet.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	21, // 20: wallet.HealthResponse.checks:type_name -> wallet.HealthCheck
	23, // 21: wallet.HealthCheck.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 22: wallet.WalletService.GenerateWallet:input_type -> wallet.GenerateWalletRequest
	4,  // 23: wallet.WalletService.ImportWallet:input_type -> wallet.ImportWalletRequest
	6,  // 24: wallet.WalletService.GetAddresses:input_type -> wallet.GetAddressesRequest
	9,  // 25: wallet.WalletService.SignTransaction:input_type -> wallet.SignTransactionRequest
	11, // 26: wallet.WalletService.SignMessage:input_type -> wallet.SignMessageRequest
	13, // 27: wallet.WalletService.VerifySignature:input_type -> wallet.VerifySignatureRequest
	15, // 28: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	17, // 29: wallet.WalletService.GetWalletInfo:input_type -> wallet.GetWalletInfoRequest
	19, // 30: wallet.WalletService.Health:input_type -> wallet.HealthRequest
	3,  // 31: wallet.WalletService.GenerateWallet:output_type -> wallet.GenerateWalletResponse
	5,  // 32: wallet.WalletService.ImportWallet:output_type -> wallet.ImportWalletResponse
	7,  // 33: wallet.WalletService.GetAddresses:output_type -> wallet.GetAddressesResponse
	10, // 34: wallet.WalletService.SignTransaction:output_type -> wallet.SignTransactionResponse
	12, // 35: wallet.WalletService.SignMessage:output_type -> wallet.SignMessageResponse
	14, // 36: wallet.WalletService.VerifySignature:output_type -> wallet.VerifySignatureResponse
	16, // 37: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	18, // 38: wallet.WalletService.GetWalletInfo:output_type -> wallet.GetWalletInfoResponse
	20, // 39: wallet.WalletService.Health:output_type -> wallet.HealthResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_proto_init() }
func file_api_proto_wallet_proto_init() {
	if File_api_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wallet_proto_rawDesc), len(file_api_proto_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_wallet_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_proto_depIdxs,
		EnumInfos:         file_api_proto_wallet_proto_enumTypes,
		MessageInfos:      file_api_proto_wallet_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_proto = out.File
	file_api_proto_wallet_proto_goTypes = nil
	file_api_proto_wallet_proto_depIdxs = nil
}
